# Generated by Django 4.1.3 on 2022-11-09 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrainPipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gubn", models.IntegerField()),
                ("gubn_nam", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "drainpipes",
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RainFall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gu_code", models.IntegerField()),
                ("gu_name", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "rainfalls",
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DetailRainFall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raingauge_code", models.IntegerField()),
                ("raingauge_name", models.CharField(max_length=10)),
                ("rainfall10", models.IntegerField()),
                ("receive_time", models.DateTimeField()),
                (
                    "gu_code",
                    models.ForeignKey(
                        db_column="gu_code_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api2.rainfall",
                    ),
                ),
            ],
            options={
                "db_table": "detailrainfall",
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DetailDrainPipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idn", models.CharField(max_length=15)),
                ("mea_ymd", models.DateTimeField()),
                ("mea_wal", models.FloatField()),
                ("sig_sta", models.CharField(max_length=20)),
                ("remark", models.TextField()),
                (
                    "gubn",
                    models.ForeignKey(
                        db_column="gubn_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api2.drainpipe",
                    ),
                ),
            ],
            options={
                "db_table": "detaildrainpipes",
                "abstract": False,
                "managed": True,
            },
        ),
    ]
