# Generated by Django 4.1.3 on 2022-11-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0002_alter_detaildrainpipe_idn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detaildrainpipe",
            name="mea_ymd",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="detailrainfall",
            name="receive_time",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name="detailrainfall",
            table="detailrainfalls",
        ),
    ]
